/// @file prop_connectivity.cpp
/// @brief Property-based tests for mesh connectivity validation and memory contiguity.
///
/// **Validates: Requirements 2.1, 2.2, 2.5, 2.6**
///
/// Property 4: Connectivity Index Range Validity
///   For any valid mesh generated by genRandomValidMesh(), all connectivity
///   indices are in [0, N-1] or INVALID_INDEX (-1), and validate_connectivity
///   returns valid=true.
///
/// Property 5: Connectivity Memory Contiguity
///   All connectivity arrays in a SyntheticMesh have contiguous storage
///   (vector::data() is contiguous, product of extents matches flat array size).
///
/// Additional property: Corrupting any single index to an out-of-range value
/// causes validate_connectivity to fail.

#include <gtest/gtest.h>
#include <rapidcheck.h>
#include <rapidcheck/gtest.h>
#include <mpas_dycore/mesh.hpp>
#include "../synthetic_mesh.hpp"

#include <cstddef>

using namespace mpas::dycore;
using namespace mpas::dycore::testing;

// Use the sentinel from the main dycore namespace (same value in both)
constexpr index_type SENTINEL = mpas::dycore::INVALID_INDEX;

// ============================================================================
// Helper: Build MeshConnectivity from a SyntheticMesh
// ============================================================================

static MeshConnectivity buildConnectivity(const SyntheticMesh& sm) {
    MeshConnectivity mc;
    mc.cellsOnEdge    = sm.cellsOnEdge_view();
    mc.verticesOnEdge = sm.verticesOnEdge_view();
    mc.edgesOnCell    = sm.edgesOnCell_view();
    mc.cellsOnCell    = sm.cellsOnCell_view();
    mc.verticesOnCell = sm.verticesOnCell_view();
    mc.cellsOnVertex  = sm.cellsOnVertex_view();
    mc.nEdgesOnCell   = sm.nEdgesOnCell_view();
    return mc;
}

// ============================================================================
// Property 4: Connectivity Index Range Validity
// ============================================================================
// For any valid mesh, validate_connectivity returns valid=true.

RC_GTEST_PROP(ConnectivityIndexRange, ValidateConnectivityPassesForValidMesh,
              ()) {
    auto mesh = *genRandomValidMesh();

    auto mc = buildConnectivity(mesh);
    auto result = validate_connectivity(mc, mesh.nCells, mesh.nEdges, mesh.nVertices);

    RC_ASSERT(result.valid);
}

// For any valid mesh, manually verify all indices are in valid range [0, N-1]
// or INVALID_INDEX.
RC_GTEST_PROP(ConnectivityIndexRange, AllIndicesInValidRange,
              ()) {
    auto mesh = *genRandomValidMesh();

    // Check cellsOnEdge: values in [0, nCells-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.cellsOnEdge.size(); ++i) {
        index_type val = mesh.cellsOnEdge[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nCells));
    }

    // Check verticesOnEdge: values in [0, nVertices-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.verticesOnEdge.size(); ++i) {
        index_type val = mesh.verticesOnEdge[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nVertices));
    }

    // Check edgesOnCell: values in [0, nEdges-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.edgesOnCell.size(); ++i) {
        index_type val = mesh.edgesOnCell[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nEdges));
    }

    // Check cellsOnCell: values in [0, nCells-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.cellsOnCell.size(); ++i) {
        index_type val = mesh.cellsOnCell[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nCells));
    }

    // Check verticesOnCell: values in [0, nVertices-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.verticesOnCell.size(); ++i) {
        index_type val = mesh.verticesOnCell[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nVertices));
    }

    // Check cellsOnVertex: values in [0, nCells-1] or INVALID_INDEX
    for (std::size_t i = 0; i < mesh.cellsOnVertex.size(); ++i) {
        index_type val = mesh.cellsOnVertex[i];
        RC_ASSERT(val == SENTINEL || (val >= 0 && val < mesh.nCells));
    }
}

// ============================================================================
// Property 5: Connectivity Memory Contiguity
// ============================================================================
// All connectivity arrays have contiguous storage and the product of extents
// equals the expected flat array size.

RC_GTEST_PROP(ConnectivityMemoryContiguity, VectorsAreContiguousAndExtentsMatchSize,
              ()) {
    auto mesh = *genRandomValidMesh();

    // cellsOnEdge: flat size should be nEdges * 2
    RC_ASSERT(mesh.cellsOnEdge.size() ==
              static_cast<std::size_t>(mesh.nEdges) * 2);

    // verticesOnEdge: flat size should be nEdges * 2
    RC_ASSERT(mesh.verticesOnEdge.size() ==
              static_cast<std::size_t>(mesh.nEdges) * 2);

    // edgesOnCell: flat size should be nCells * maxEdges
    RC_ASSERT(mesh.edgesOnCell.size() ==
              static_cast<std::size_t>(mesh.nCells) * mesh.maxEdges);

    // cellsOnCell: flat size should be nCells * maxEdges
    RC_ASSERT(mesh.cellsOnCell.size() ==
              static_cast<std::size_t>(mesh.nCells) * mesh.maxEdges);

    // verticesOnCell: flat size should be nCells * maxEdges
    RC_ASSERT(mesh.verticesOnCell.size() ==
              static_cast<std::size_t>(mesh.nCells) * mesh.maxEdges);

    // cellsOnVertex: flat size should be nVertices * 3
    RC_ASSERT(mesh.cellsOnVertex.size() ==
              static_cast<std::size_t>(mesh.nVertices) * 3);

    // nEdgesOnCell: flat size should be nCells
    RC_ASSERT(mesh.nEdgesOnCell_arr.size() ==
              static_cast<std::size_t>(mesh.nCells));
}

RC_GTEST_PROP(ConnectivityMemoryContiguity, MdspanExtentsMatchFlatArraySize,
              ()) {
    auto mesh = *genRandomValidMesh();

    // Build ConnectivityView objects and verify extents product matches vector size
    auto cellsOnEdge_v = mesh.cellsOnEdge_view();
    RC_ASSERT(cellsOnEdge_v.extent(0) == static_cast<std::size_t>(mesh.nEdges));
    RC_ASSERT(cellsOnEdge_v.extent(1) == 2u);
    RC_ASSERT(cellsOnEdge_v.extent(0) * cellsOnEdge_v.extent(1) ==
              mesh.cellsOnEdge.size());

    auto verticesOnEdge_v = mesh.verticesOnEdge_view();
    RC_ASSERT(verticesOnEdge_v.extent(0) == static_cast<std::size_t>(mesh.nEdges));
    RC_ASSERT(verticesOnEdge_v.extent(1) == 2u);
    RC_ASSERT(verticesOnEdge_v.extent(0) * verticesOnEdge_v.extent(1) ==
              mesh.verticesOnEdge.size());

    auto edgesOnCell_v = mesh.edgesOnCell_view();
    RC_ASSERT(edgesOnCell_v.extent(0) == static_cast<std::size_t>(mesh.nCells));
    RC_ASSERT(edgesOnCell_v.extent(1) == static_cast<std::size_t>(mesh.maxEdges));
    RC_ASSERT(edgesOnCell_v.extent(0) * edgesOnCell_v.extent(1) ==
              mesh.edgesOnCell.size());

    auto cellsOnCell_v = mesh.cellsOnCell_view();
    RC_ASSERT(cellsOnCell_v.extent(0) == static_cast<std::size_t>(mesh.nCells));
    RC_ASSERT(cellsOnCell_v.extent(1) == static_cast<std::size_t>(mesh.maxEdges));
    RC_ASSERT(cellsOnCell_v.extent(0) * cellsOnCell_v.extent(1) ==
              mesh.cellsOnCell.size());

    auto verticesOnCell_v = mesh.verticesOnCell_view();
    RC_ASSERT(verticesOnCell_v.extent(0) == static_cast<std::size_t>(mesh.nCells));
    RC_ASSERT(verticesOnCell_v.extent(1) == static_cast<std::size_t>(mesh.maxEdges));
    RC_ASSERT(verticesOnCell_v.extent(0) * verticesOnCell_v.extent(1) ==
              mesh.verticesOnCell.size());

    auto cellsOnVertex_v = mesh.cellsOnVertex_view();
    RC_ASSERT(cellsOnVertex_v.extent(0) == static_cast<std::size_t>(mesh.nVertices));
    RC_ASSERT(cellsOnVertex_v.extent(1) == 3u);
    RC_ASSERT(cellsOnVertex_v.extent(0) * cellsOnVertex_v.extent(1) ==
              mesh.cellsOnVertex.size());
}

RC_GTEST_PROP(ConnectivityMemoryContiguity, DataPointersAreContiguous,
              ()) {
    auto mesh = *genRandomValidMesh();

    // For std::vector, data() always points to a contiguous block.
    // Verify that the ConnectivityView data_handle matches the vector's data().
    auto cellsOnEdge_v = mesh.cellsOnEdge_view();
    RC_ASSERT(cellsOnEdge_v.data_handle() == mesh.cellsOnEdge.data());

    auto verticesOnEdge_v = mesh.verticesOnEdge_view();
    RC_ASSERT(verticesOnEdge_v.data_handle() == mesh.verticesOnEdge.data());

    auto edgesOnCell_v = mesh.edgesOnCell_view();
    RC_ASSERT(edgesOnCell_v.data_handle() == mesh.edgesOnCell.data());

    auto cellsOnCell_v = mesh.cellsOnCell_view();
    RC_ASSERT(cellsOnCell_v.data_handle() == mesh.cellsOnCell.data());

    auto verticesOnCell_v = mesh.verticesOnCell_view();
    RC_ASSERT(verticesOnCell_v.data_handle() == mesh.verticesOnCell.data());

    auto cellsOnVertex_v = mesh.cellsOnVertex_view();
    RC_ASSERT(cellsOnVertex_v.data_handle() == mesh.cellsOnVertex.data());
}

// ============================================================================
// Property: Corrupting a single index to out-of-range causes validation failure
// ============================================================================
// For any valid mesh, picking a random connectivity array and corrupting one
// entry to an out-of-range value causes validate_connectivity to return
// valid=false.

RC_GTEST_PROP(ConnectivityCorruption, SingleOutOfRangeIndexCausesValidationFailure,
              ()) {
    auto mesh = *genRandomValidMesh();

    // Choose which connectivity table to corrupt (0-5)
    const auto tableIdx = *rc::gen::inRange(0, 6);

    // Get the target vector and its entity count upper bound
    std::vector<index_type>* target = nullptr;
    index_type entityCount = 0;

    switch (tableIdx) {
        case 0: target = &mesh.cellsOnEdge;    entityCount = mesh.nCells;    break;
        case 1: target = &mesh.verticesOnEdge; entityCount = mesh.nVertices; break;
        case 2: target = &mesh.edgesOnCell;    entityCount = mesh.nEdges;    break;
        case 3: target = &mesh.cellsOnCell;    entityCount = mesh.nCells;    break;
        case 4: target = &mesh.verticesOnCell; entityCount = mesh.nVertices; break;
        case 5: target = &mesh.cellsOnVertex;  entityCount = mesh.nCells;    break;
    }

    RC_PRE(target != nullptr && !target->empty());

    // Choose a random position to corrupt
    const auto pos = *rc::gen::inRange<std::size_t>(0, target->size());

    // Generate an out-of-range value: either >= entityCount or < -1
    const auto corrupt_type = *rc::gen::inRange(0, 2);
    index_type bad_value;
    if (corrupt_type == 0) {
        // Value >= entityCount (one or more past valid range)
        bad_value = entityCount + *rc::gen::inRange(0, 100);
    } else {
        // Value < INVALID_INDEX (-1), i.e., -2 or less
        bad_value = -2 - *rc::gen::inRange(0, 100);
    }

    (*target)[pos] = bad_value;

    // Validate should now fail
    auto mc = buildConnectivity(mesh);
    auto result = validate_connectivity(mc, mesh.nCells, mesh.nEdges, mesh.nVertices);

    RC_ASSERT(!result.valid);
    RC_ASSERT(result.bad_value == bad_value);
}
